# Generated by Django 4.0.5 on 2024-07-21 16:16

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mzalendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True)),
                ('county', models.CharField(blank=True, choices=[('Mombasa', 'Mombasa'), ('Nairobi City', 'Nairobi City'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Kwale', 'Kwale'), ('Kakamega', 'Kakamega'), ('Moyale', 'Moyale'), ('Busia', 'Busia'), ('Kiambu', 'Kiambu'), ('Nyamira', 'Nyamira'), ('Vihiga', 'Vihiga'), ('Machakos', 'Machakos'), ('Embu', 'Embu'), ('Bomet', 'Bomet'), ('Meru', 'Meru'), ('Uasin Gishu', 'Uasin Gishu'), ('Bungoma', 'Bungoma'), ('Siaya', 'Siaya'), ('Narok', 'Narok'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Nyeri', 'Nyeri'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Makueni', 'Makueni'), ('Kisii', 'Kisii'), ('Kirinyaga', 'Kirinyaga'), ('Kitui', 'Kitui'), ('Kericho', 'Kericho'), ('Nyandarua', 'Nyandarua'), ('Marsabit', 'Marsabit'), ('Homa Bay', 'Homa Bay'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Taita Taveta', 'Taita Taveta'), ('Isiolo', 'Isiolo'), ('Samburu', 'Samburu'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ("Murang'a", "Murang'a"), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia')], max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('life', models.TextField(blank=True, null=True)),
                ('dod', models.DateField(blank=True, null=True, verbose_name='Date Deceased')),
                ('author', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Cover Image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=home.models.Mzalendo.generate_slug, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mzalendo_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.IntegerField(default=0, verbose_name=((0, 'Active'), (1, 'Completed'), (2, 'Due Date Passed')))),
            ],
            options={
                'ordering': ['-date_assigned'],
            },
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifier_approvedby', to=settings.AUTH_USER_MODEL)),
                ('mzalendo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.mzalendo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mzalendo_comments', to='home.mzalendo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
