# Generated by Django 3.0.4 on 2020-05-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_assigned']},
        ),
    ]
